import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

const routes = [
    "index.html", "about.html", "blog.html",
    "chat.html", "guestbook.html", "reader.html",
    "resources.html"
] as const;

const errors: string[] = [];
const matches = (html: string, re: RegExp): string[] =>
    Array.from(html.matchAll(re), (match) => match[1] ?? "");

for (const path of routes) {
    const html = await readFile(resolve(path), "utf8");
    const frameIds = matches(html, /\bdata-kc-static-window="([^"]+)"/g);
    const launcherIds = matches(html, /\bdata-kc-static-window-launcher="([^"]+)"/g);

    if (!html.includes('data-kc-static-shell="1"')) errors.push(path + ": static navigation missing");
    if (!html.includes('id="main-menu-links"')) errors.push(path + ": navigation links missing");
    if (!html.includes('id="main-menu-themes"')) errors.push(path + ": theme picker missing");
    if (!html.includes('id="kc-static-ui-data"')) errors.push(path + ": embedded UI configuration missing");
    if (!/<footer\b[^>]*\bid="main-footer"[^>]*>\s*[^\s<]/i.test(html)) {
        errors.push(path + ": empty generated footer");
    }

    // RSS's static controls must be generated by the build, never duplicated by hydration.
    if ((path === "blog.html" || path === "resources.html") && !html.includes('data-rss-built="1"')) {
        errors.push(path + ": build-time RSS content mount missing");
    }
    if ((path === "blog.html" || path === "resources.html") && !html.includes('class="rss-loading"')) {
        errors.push(path + ": RSS loading placeholder missing");
    }
    if (path === "blog.html" && !html.includes('data-kc-static-rss-shell="1"')) {
        errors.push(path + ": build-time filter drawer missing");
    }
    if (path === "blog.html" && !html.includes('data-rss-filters-toggle="1"')) {
        errors.push(path + ": filter toggle missing");
    }
    if (path === "blog.html" && !html.includes('id="kc-blog-author-filter"')) {
        errors.push(path + ": author filter mount missing");
    }
    if (path === "blog.html" && matches(html, /id="kc-blog-cal-filter"/g).length !== 1) {
        errors.push(path + ": calendar mount should occur exactly once");
    }
    if (path === "resources.html" && html.includes('data-kc-static-rss-shell="1"')) {
        errors.push(path + ": resources must not receive blog-only filters");
    }

    if (frameIds.length === 0) errors.push(path + ": no pre-rendered window frames");
    if (frameIds.length !== new Set(frameIds).size) {
        errors.push(path + ": duplicate pre-rendered window ids");
    }
    if (frameIds.length !== launcherIds.length) {
        errors.push(path + ": frame and launcher counts differ");
    }

    for (const id of frameIds) {
        if (!html.includes(`id="${id}-header"`)) errors.push(path + ": missing window header: " + id);
        if (!html.includes(`id="${id}-body"`)) errors.push(path + ": missing window body: " + id);
        if (!html.includes(`id="window-api-launcher-${id}"`)) errors.push(path + ": missing launcher: " + id);
    }

    console.log(`[shells] ${path}: ${frameIds.length} pre-rendered windows`);
}

for (const error of errors) console.error("[shells] " + error);

if (errors.length > 0) process.exitCode = 1;
else console.log("[shells] Seven shared pages have pre-rendered navigation, footer, controls and window frames.");
